#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="mode t setup.py"

set -x

${PREFIX}ruff check $SOURCE_FILES --diff
${PREFIX}ruff format $SOURCE_FILES --check --diff
# ${PREFIX}mypy $SOURCE_FILES
