#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="mode tests setup.py"

set -x

${PREFIX}ruff check $SOURCE_FILES --fix
${PREFIX}ruff format $SOURCE_FILES
