#!/bin/sh

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -ex

# if [ -z $GITHUB_ACTIONS ]; then
#     scripts/check
# fi

${PREFIX}pytest tests/unit tests/functional

# if [ -z $GITHUB_ACTIONS ]; then
#     scripts/coverage
# fi
# #!/usr/bin/env bash

# set -e
# set -x

# pytest tests --cov=mode
